import { tool } from "ai";
import { z } from "zod";

import { getLatestInsights } from "@/lib/services/chat-tool-services/insights-service";

import type { ChatToolContext } from "./shared/tool-context";

const inputSchema = z.object({});

export function createInsightsLatestTool(ctx: ChatToolContext) {
  return tool({
    description:
      "Fetch the most recent batch of dashboard insight cards (trends, anomalies, milestones generated by the insight pipeline). " +
      "Use when the user asks 'what's new?', 'what insights do you have?', or anything referencing the dashboard insight feed.",
    inputSchema,
    execute: async () => {
      ctx.emitStatus("Fetching latest insights…");
      return getLatestInsights(
        { teamId: ctx.workspace.teamId },
        { supabase: ctx.supabaseClient }
      );
    },
  });
}
